In [2]:
!pip install einops

In [3]:
import torch
from TransUNet import TransUNet

model = TransUNet(
    img_dim= 128,
    patch_dim= 16,
    in_channels= 3, 
    classes= 2, 
    blocks= 6,
    heads= 8,
    linear_dim= 1024
)

x = torch.randn(1, 3, 128, 128)
model(x) # (2, 128, 128)

RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:76] data. DefaultCPUAllocator: not enough memory: you tried to allocate 154618822656 bytes.

In [4]:
import torch
from MLP_Mixer import MLPMixer

model = MLPMixer(
    classes= 10,
    blocks= 6,
    img_dim= 128,
    patch_dim= 128,
    in_channels= 3,
    dim= 512,
    token_dim= 256,
    channel_dim= 2048
)

x = torch.randn(1, 3, 128, 128)
model(x) # (1, 10)

tensor([[-0.3642,  0.2571,  0.0019,  0.3146,  0.2235, -0.2387,  0.1831, -0.1223,
         -0.1673,  0.3851]], grad_fn=<AddmmBackward0>)

In [5]:
import torch
from ViT import ViT

model = ViT(
    img_dim= 128,
    in_channels= 3,
    patch_dim= 16,
    classes= 10,
    dim= 512,
    blocks= 6,
    heads= 4,
    linear_dim= 1024,
    classification= True 
)

x = torch.randn(1, 3, 128, 128)
model(x) # (1, 10)

d:\LocalGit\SOTA-Vision\Transformer.py:38: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  attention = nn.Softmax()(energy)


tensor([[ 0.8230, -0.1678, -0.0243,  0.2090,  0.2835,  0.6111,  0.2898, -0.0777,
         -0.1889, -0.5868]], grad_fn=<AddmmBackward0>)

In [6]:
import torch
from fastformer import FastFormer

model = FastFormer(
    in_dims= 256, 
    token_dim= 512, 
    num_heads= 8
)

x = torch.randn(1, 128, 256)
model(x) # (1, 128, 512)

tensor([[[-0.1273, -0.3293, -0.1559,  ..., -0.3576, -0.7974, -0.2983],
         [-0.1821, -0.0961,  0.2544,  ..., -0.5601, -0.2094, -0.0518],
         [ 0.3089,  0.0714,  0.0763,  ...,  0.0894, -0.2127,  0.3902],
         ...,
         [-0.0335, -0.2933,  0.7046,  ...,  0.0782, -0.0200, -0.2699],
         [-0.3986, -0.2651,  0.2963,  ..., -0.6638, -0.1879, -0.3330],
         [ 0.0344,  0.2605,  0.3976,  ...,  0.3685, -0.0598,  0.4268]]],
       grad_fn=<AddBackward0>)

In [7]:
import torch
from han import HAN

model = HAN(in_channels= 3)

x = torch.randn(1, 3, 256, 256)
model(x) # (1, 3, 512, 512)

d:\LocalGit\SOTA-Vision\han.py:166: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x += x_1 + self.lam(self.softmax(x_2))


tensor([[[[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]]]], grad_fn=<SigmoidBackward0>)